project:
  type: book

book:
  title: "Building Reproducible Analytical Pipelines"
  subtitle: "Master of Data Science, University of Luxembourg - 2025"
  author: "Bruno Rodrigues"
  date: "2025-09-15"
  search: true
  repo-url: "https://github.com/b-rodrigues/rap4mads_2025"
  repo-actions: [edit]
  sharing: [twitter, facebook]
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - 02-intro-nix.qmd
    - 03-git.qmd
    - 04-functional-programming.qmd
    - 05-unit-testing.qmd
    - 06-packages.qmd
    - 07-rixpress.qmd
    - 08-docker.qmd
  page-navigation: true

bibliography: references.bib

format:
  epub:
    toc:
      true
    lang:
      en-GB
    date:
      "2025-09-15"
    css:
      epub.css
  html:
    include-in-header:
      file: header.html
    theme:
      light: flatly
      dark: solar
    css:
      epub.css
  pdf:
    keep-tex: true
    documentclass: scrbook
    classoption: [paper=6in:9in,pagesize=pdftex,headinclude=on,footinclude=on,12pt]
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \areaset[0.50in]{4.5in}{8in}
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
           showspaces = false,
           showtabs = false,
           breaksymbolleft={},
           breaklines
           % Note: setting commandchars=\\\{\} here will cause an error 
        }  
    fig-pos: 'H'
